name: Update RSS Feeds
on:
  schedule:
    # RSS抓取：UTC 22:00, 03:00, 12:00 (北京时间 06:00, 11:00, 20:00)
    - cron: '0 22 * * *'
    - cron: '0 3 * * *'
    - cron: '0 12 * * *'
    # 邮件发送：UTC 00:00 (北京时间 08:00)
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-feeds:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Set up Python environment
      run: |
        python3 -m pip install --upgrade pip
        pip3 install feedparser pytz pyyaml
    
    - name: Fetch RSS feeds
      run: |
        python3 fetch_feeds.py
    
    - name: Get current hour (UTC)
      id: current-hour
      run: echo "hour=$(date -u '+%H')" >> $GITHUB_OUTPUT
    
    - name: Send email notification
      if: github.event.schedule == '0 0 * * *' || (github.event_name == 'workflow_dispatch' && contains(github.event.inputs.action, 'email'))
      env:
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
      run: |
        python3 send_email.py --time-window 24
    
    - name: Deploy
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add -A
        git diff-index --quiet HEAD || git commit -m "Update posts"
        git push origin HEAD:main